resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/7thwik/Parameter
    branch: master
jobs:
- name: show-animal-names
  plan:
  - get: git-repo
  - task: show-animal-names
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: git-repo
      run:
        path: ./git-repo/pc.sh
      params:
        CAT_NAME: ((cat-name))
        DOG_NAME: ((dog-name))
